# Generated by Django 2.2.5 on 2020-03-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='sku',
            field=models.UUIDField(default=0),
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ManyToManyField(blank=True, to='web.Category'),
        ),
    ]
