# Generated by Django 2.2.5 on 2020-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200309_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sku',
            field=models.IntegerField(default=0),
        ),
    ]
